import type { Product } from "../types/product"

export const  data: Product[] = [
    {
        id: 1,
        title: "Nike Air Monarch IV",
        img: "https://imgs.search.brave.com/J-I21iKhh5Pke3dmk0e-HHd4JhhUWv7aCnmVzTOfHtk/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMubmlrZS5jb20v/YS9pbWFnZXMvdF9k/ZWZhdWx0L3Vpcnlw/cXF4cTgzbXdjamJm/OWVqL0FJUitNT05B/UkNIK0lWLnBuZw",
        rating: 4,
        reviews: "(123 reviews)",
        prevPrice: 200,
        newPrice: 100,
        company: "Nike",
        brand: "Nike",
        color: "White",
        category: "sneakers",
    },
    {
        id: 2,
        title: "Nike Air Vapormax Plus",
        img: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80",
        rating: 4,
        reviews: "(145 reviews)",
        prevPrice: 220,
        newPrice: 140,
        company: "Nike",
        brand: "Nike",
        color: "Red",
        category: "sneakers",
    },
    {
        id: 3,
        title: "Adidas Ultraboost 21",
        img: "https://imgs.search.brave.com/toG78FnczeP-sJ9jF3kjhhin3OyRDl4DE_QdBsBlsT4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5zZWxmLmNvbS9w/aG90b3MvNjAxYWQ0/NjlhNWIxYWQzY2Q1/Mzk3YWM4LzE6MS93/XzM2MCxjX2xpbWl0/L0FkaWRhc1VsdHJh/Ym9vc3QuanBn",
        rating: 4,
        reviews: "(98 reviews)",
        prevPrice: 180,
        newPrice: 120,
        company: "Adidas",
        brand: "Adidas",
        color: "White",
        category: "running",
    },
    {
        id: 4,
        title: "Puma RS-X",
        img: "https://imgs.search.brave.com/Q7E4p7DOR4oTbfcEPYEcAS1tqscX_d_nOIyL56LpA2c/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NTFlTkp1TmhEOEwu/anBn",
        rating: 4,
        reviews: "(76 reviews)",
        prevPrice: 150,
        newPrice: 90,
        company: "Puma",
        brand: "Puma",
        color: "White",
        category: "casual",
    },
    {
        id: 5,
        title: "Converse Chuck Taylor",
        img: "https://imgs.search.brave.com/r7jNcmgookE2syCijxvY2y42wDlE9UDWauLBU3CAVBs/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/aW5keS5jb20uYXIv/Y2RuL3Nob3AvZmls/ZXMvY29udmVyc2Ut/bGlmdC1kb3VibGUt/c3RhY2stbG9uYS1t/dWplci1jaG9jbG8t/bmVncm9zLWExNTQ5/MGMtNl8wdGV0a2Jq/bWR5NThvaHhvLVBo/b3Rvcm9vbS5qcGc_/dj0xNzUxOTAyNjk0/JndpZHRoPTUzMw",
        rating: 4,
        reviews: "(210 reviews)",
        prevPrice: 80,
        newPrice: 60,
        company: "Converse",
        brand: "Converse",
        color: "Black",
        category: "classic",
    },
    {
        id: 6,
        title: "Vans Old Skool",
        img: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80",
        rating: 4,
        reviews: "(134 reviews)",
        prevPrice: 70,
        newPrice: 50,
        company: "Vans",
        brand: "Vans",
        color: "Black",
        category: "skate",
    },
    // ---- New Added Products ----
    {
        id: 7,
        title: "New Balance 574",
        img: "https://imgs.search.brave.com/auPvm-GL47CU_BzDPLpPuG2HsACfyVl3YTDbas8VCRg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMuZm9vdGxvY2tl/ci5jb20vaXMvaW1h/Z2UvRUJGTDIvSUM1/NzRFVkc_d2lkPTI1/MCZoZWk9MjUw",
        rating: 5,
        reviews: "(89 reviews)",
        prevPrice: 120,
        newPrice: 85,
        company: "New Balance",
        brand: "New Balance",
        color: "Grey",
        category: "casual",
    },
    {
        id: 8,
        title: "Reebok Classic Leather",
        img: "https://imgs.search.brave.com/MsSwH4Uh5mjPKdzAG-cAACLxFo2nefTFYrrlCg9ASvU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9wcmV2/aWV3LnJlZGQuaXQv/ZGlmZmVyZW5jZS1i/ZXR3ZWVuLWNsYXNz/aWMtbGVhdGhlci1z/bmVha2VyLWFuZC1y/ZWVib2stZ2xpZGUt/djAtZmFreHJkcjQy/bW1iMS5qcGc_d2lk/dGg9MjA0OCZmb3Jt/YXQ9cGpwZyZhdXRv/PXdlYnAmcz02MDNk/ZGEzY2Y1NjY2NWQ1/MTdhYTg3MTc1NmJh/NmY3Mzg3OGQzMWNi",
        rating: 4,
        reviews: "(102 reviews)",
        prevPrice: 110,
        newPrice: 75,
        company: "Reebok",
        brand: "Reebok",
        color: "White",
        category: "classic",
    },
    {
        id: 9,
        title: "Asics Gel-Kayano 27",
        img: "https://imgs.search.brave.com/MPSjwzP5zh_wZBaSzLw1T5Pb4wnSa74Ux0G8IjIIMxs/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWcu/cnVubmluZ3dhcmVo/b3VzZS5jb20vd2F0/ZXJtYXJrL3JzZy5w/aHA_cGF0aD0vY29u/dGVudF9pbWFnZXMv/cmV2aWV3cy9BU0lD/U19LYXlhbm9fMjcv/QUsyN00wMS1SMS5q/cGcmbnc9NzI4",
        rating: 5,
        reviews: "(67 reviews)",
        prevPrice: 160,
        newPrice: 120,
        company: "Asics",
        brand: "Asics",
        color: "Red",
        category: "running",
    },
    {
        id: 10,
        title: "Jordan 1 Retro High",
        img: "https://imgs.search.brave.com/UIigys4Ppe7Cr-5uBuxqdw5loDHUZRprAQA7DQF8Pps/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jcmVw/ZG9nY3Jldy5jb20v/Y2RuL3Nob3AvcHJv/ZHVjdHMvSk9SREFO/MVJFVFJPSElHSFNI/QURPVzJfMS5wbmc_/dj0xNzU1MDk3MzU3/JndpZHRoPTE1MDA",
        rating: 5,
        reviews: "(312 reviews)",
        prevPrice: 250,
        newPrice: 200,
        company: "Jordan",
        brand: "Jordan",
        color: "Grey",
        category: "sneakers",
    },
    {
        id: 11,
        title: "Fila Disruptor II",
        img: "https://imgs.search.brave.com/BZV9zc7niMMfxggDCzhah3P6yw10etfaoIqBqPneNLA/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/bWVkaWEuYW1wbGll/bmNlLm5ldC9pL29m/ZmljZS8zMjEwMjEw/MDYwX3ByMS5qcGc_/JGhpZ2hyZXMkJmZt/dD1hdXRvJnFsdD1k/ZWZhdWx0JmZtdC5q/cGVnLmludGVybGFj/ZWQ9dHJ1ZQ",
        rating: 4,
        reviews: "(156 reviews)",
        prevPrice: 95,
        newPrice: 70,
        brand: "Fila",
        company: "Fila",
        color: "White",
        category: "casual",
    },
    {
        id: 12,
        title: "Balenciaga Triple S",
        img: "https://imgs.search.brave.com/oyy-uBJgvlWuWmLdjIcWO6ZT1yb5nXeVA7M0bzYJbmA/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/d2FsbGFwb3AuY29t/L2ltYWdlcy8xMDQy/MC9neC9lby9fXy9j/MTA0MjBwMTAyMzU3/MTM2Mi9pNDk5MTg0/ODA4Ni5qcGc_cGlj/dHVyZVNpemU9VzMy/MA",
        rating: 5,
        reviews: "(45 reviews)",
        prevPrice: 850,
        newPrice: 720,
        brand: "Balenciaga",
        company: "Balenciaga",
        color: "Multi",
        category: "luxury",
    },
    // ---- More Added Products ----
{
    id: 13,
    title: "Under Armour HOVR Phantom 2",
    img: "https://imgs.search.brave.com/Utwor3FSsnOjJBMMFh687t1YaWpMGmVRJhDI4zo3r0w/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/c2hvcGlmeS5jb20v/cy9maWxlcy8xLzA2/MDMvMzAzMS8xODc1/L3Byb2R1Y3RzL21h/aW4tc3F1YXJlXzZh/NjY4MmE2LTBlZjct/NDNlMC1hYzk2LWZj/MWQxOGNjODU2M194/NDgwLmpwZz93PTM4/NCZ2PTE2OTM5MTIy/MzU",
    rating: 4,
    reviews: "(78 reviews)",
    prevPrice: 140,
    newPrice: 110,
    company: "Under Armour",
    brand: "Under Armour",
    color: "Black",
    category: "running",
},
{
    id: 14,
    title: "Salomon Speedcross 5",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMhko3c8dMx3MDTojS7eq1KPZ1gSqRcSLaczWQFxcSw50SsYa817Yx2uUUDD0fD2nhsUU&usqp=CAU",
    rating: 5,
    reviews: "(55 reviews)",
    prevPrice: 160,
    newPrice: 130,
    company: "Salomon",
    brand: "Salomon",
    color: "Blue",
    category: "trail",
},
{
    id: 15,
    title: "Saucony Endorphin Speed 2",
    img: "https://acdn-us.mitiendanube.com/stores/001/153/552/products/s20687-16-11-38b478e75cdc538a1a16636191734132-640-0.jpg",
    rating: 5,
    reviews: "(92 reviews)",
    prevPrice: 200,
    newPrice: 150,
    company: "Saucony",
    brand: "Saucony",
    color: "Yellow",
    category: "running",
},
{
    id: 16,
    title: "Mizuno Wave Rider 24",
    img: "https://runpacers.com/cdn/shop/files/Womens-Mizuno-Wave-Rider-29-White-Icelandic-Blue.jpg?v=1751398011&width=533",
    rating: 4,
    reviews: "(63 reviews)",
    prevPrice: 170,
    newPrice: 120,
    company: "Mizuno",
    brand: "Mizuno",
    color: "White",
    category: "running",
},
{
    id: 17,
    title: "Brooks Ghost 14",
    img: "https://res.cloudinary.com/dr9fn4qkg/image/upload/q_auto/w_400/brooks-images/product-img/110369_067_l_wr.png",
    rating: 5,
    reviews: "(81 reviews)",
    prevPrice: 150,
    newPrice: 110,
    company: "Brooks",
    brand: "Brooks",
    color: "Grey",
    category: "running",
},
{
    id: 18,
    title: "On Cloud X",
    img: "https://cdn.shopify.com/s/files/1/0129/6942/files/on-running-womens-cloud-x-4-running-shoe-all-black.jpg?v=1728671589",
    rating: 4,
    reviews: "(66 reviews)",
    prevPrice: 140,
    newPrice: 100,
    company: "On",
    brand: "On",
    color: "Black",
    category: "training",
},
{
    id: 19,
    title: "Hoka One One Clifton 8",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqVri7SpEu6j_2fU9bgD-mDTtaJ7TO83hH2Q&s",
    rating: 5,
    reviews: "(72 reviews)",
    prevPrice: 160,
    newPrice: 130,
    company: "Hoka",
    brand: "Hoka One One",
    color: "Blue",
    category: "running",
},
{
    id: 20,
    title: "Skechers D'Lites",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqzqTxn00cS7PxmnEGOql7S9uZzI7289UF1w&s",
    rating: 4,
    reviews: "(145 reviews)",
    prevPrice: 90,
    newPrice: 65,
    company: "Skechers",
    brand: "Skechers",
    color: "White",
    category: "casual",
},
{
    id: 21,
    title: "Timberland 6-Inch Premium Boots",
    img: "https://img01.ztat.net/article/spp-media-p1/cb606e140f934a1692f0d071720dd892/1c375350934f4e029df9cb8f28634fca.jpg?imwidth=1800&filter=packshot",
    rating: 5,
    reviews: "(210 reviews)",
    prevPrice: 190,
    newPrice: 160,
    company: "Timberland",
    brand: "Timberland",
    color: "Brown",
    category: "boots",
},
{
    id: 22,
    title: "Dr. Martens 1460",
    img: "https://cdn.media.amplience.net/i/office/2760304361_sd1.jpg?$newhighres$&fmt=auto&qlt=default&fmt.jpeg.interlaced=true",
    rating: 5,
    reviews: "(178 reviews)",
    prevPrice: 170,
    newPrice: 140,
    company: "Dr. Martens",
    brand: "Dr. Martens",
    color: "Black",
    category: "boots",
},
{
    id: 23,
    title: "Clarks Desert Boot",
    img: "https://www.clarksstores.ae/cdn/shop/products/26155527_1.jpg?v=1658823327",
    rating: 4,
    reviews: "(89 reviews)",
    prevPrice: 150,
    newPrice: 120,
    company: "Clarks",
    brand: "Clarks",
    color: "Beige",
    category: "boots",
},
{
    id: 24,
    title: "UGG Classic Mini II",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-96dASyZ1hJQa5tu0Sg30iIwAB6zC55K_Z_ZMurGpXz60JcbHDfMRBfZrv3CN1MhqlGA&usqp=CAU",
    rating: 4,
    reviews: "(132 reviews)",
    prevPrice: 140,
    newPrice: 110,
    company: "UGG",
    brand: "UGG",
    color: "Chestnut",
    category: "boots",
},
{
    id: 25,
    title: "Birkenstock Arizona",
    img: "https://m.media-amazon.com/images/I/71qShd8r87S._UY300_.jpg",
    rating: 4,
    reviews: "(120 reviews)",
    prevPrice: 100,
    newPrice: 80,
    company: "Birkenstock",
    brand: "Birkenstock",
    color: "Brown",
    category: "sandals",
},
{
    id: 26,
    title: "Crocs Classic Clog",
    img: "https://lemmonsstore.com.au/cdn/shop/files/jd_ANZ0118350_b.jpg?v=1714094454&width=1214",
    rating: 4,
    reviews: "(300 reviews)",
    prevPrice: 60,
    newPrice: 45,
    company: "Crocs",
    brand: "Crocs",
    color: "Green",
    category: "sandals",
},
{
    id: 27,
    title: "Teva Hurricane XLT2",
    img: "https://al-ikhsan.com/cdn/shop/files/1019234-CYB_1_2b707885-207f-48f8-97b4-066d0d70f54d.jpg?v=1735287540",
    rating: 4,
    reviews: "(98 reviews)",
    prevPrice: 75,
    newPrice: 55,
    company: "Teva",
    brand: "Teva",
    color: "Black",
    category: "sandals",
},
{
    id: 28,
    title: "Columbia Newton Ridge Plus",
    img: "https://img01.ztat.net/article/spp-media-p1/224c47dde7f54db387da61a253ea4e68/2d6c4616496d48b3811359e792eaa0ba.jpg?imwidth=1800&filter=packshot",
    rating: 4,
    reviews: "(140 reviews)",
    prevPrice: 130,
    newPrice: 100,
    company: "Columbia",
    brand: "Columbia",
    color: "Brown",
    category: "hiking",
},
{
    id: 29,
    title: "Merrell Moab 2 Ventilator",
    img: "https://i.ebayimg.com/images/g/IlEAAOSw~VRkQZfe/s-l1200.jpg",
    rating: 5,
    reviews: "(165 reviews)",
    prevPrice: 120,
    newPrice: 95,
    company: "Merrell",
    brand: "Merrell",
    color: "Grey",
    category: "hiking",
},
{
    id: 30,
    title: "La Sportiva Bushido II",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxu7vOVqlmxg92rP7Chloh_R032jSXYKI-AQ&s",
    rating: 5,
    reviews: "(60 reviews)",
    prevPrice: 160,
    newPrice: 130,
    company: "La Sportiva",
    brand: "La Sportiva",
    color: "Red",
    category: "trail",
},
{
    id: 31,
    title: "Patagonia Activist Sneakers",
    img: "https://i.ebayimg.com/images/g/6FYAAOSw8uJnmuWy/s-l300.jpg",
    rating: 4,
    reviews: "(42 reviews)",
    prevPrice: 140,
    newPrice: 110,
    company: "Patagonia",
    brand: "Patagonia",
    color: "Blue",
    category: "casual",
},
{
    id: 32,
    title: "Allbirds Wool Runners",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTII1KQHL9mQHqFlnPdR5eVHb2vCoOUipuzFA&s",
    rating: 5,
    reviews: "(230 reviews)",
    prevPrice: 125,
    newPrice: 95,
    company: "Allbirds",
    brand: "Allbirds",
    color: "Grey",
    category: "casual",
},

]

export default data

export const brands = ["All", ...Array.from(new Set(data.map(p => p.brand)))];
export const categories = ["All", ...Array.from(new Set(data.map(p => p.category)))];
// Price ranges (static example)
export const prices = ["All", "$0 - $50", "$51 - $100", "$101 - $200", "$200+"];

// Colors (with hex values for UI circles)
export const colors = [
  { name: "All", hex: "#ffffff" },
  { name: "Black", hex: "#000000" },
  { name: "Red", hex: "#ef4444" },
  { name: "Blue", hex: "#3b82f6" },
  { name: "Green", hex: "#22c55e" },
  { name: "White", hex: "#f9fafb" },
  { name: "Grey", hex: "#989898"},
  { name: "Brown", hex: "#a855f7"},
  { name: "Yellow", hex: "#fbbf24"},
  { name: "Beige", hex: "#f59e0b"},
  { name: "Chestnut", hex: "#b91c1c"},
];